### your site title here

title: Haider Ali
description: Game Designer | Solar Sailor | Ontario Tech Game Dev 2020 - 2024

baseurl: / #name of GitHub repository
url: "" #custom url to be used instead of GitHub repository
email: Haiderali360@gmail.com #

# Pagination
paginate: 4
permalink: /blog/:year/:title/
paginate_path: /blog/page:num/

# Social media links in footer
twitter: "SinbadThePoet"
linkedin: "haideralisolar"
github: "sinbadthepoet"
instagram: "haiderali.exe"


# Markdown
highlighter: rouge
markdown: kramdown

# Tracker
analytics:

# optimization -> compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

#collection
collections:
  projects:
    output: true
    permalink: /projects/:name/
    order:
      - BALISSET.md
      - FarCryDroneOperator.md
      - Dishonored3.md
      - DebtLockedDual.md
      - Boomerangers.md
      - ProjectFlow.md
      - GameJams.md
      - WageCage.md
      - Resume.md

sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages

exclude:
  - README.md
  - LICENSE.md

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-email-protect
  - jekyll-target-blank
